siteName: L'Atelier des Cousettes
email: info@couture-tarn.fr
phones:
  - 06.95.78.36.34
  - 05.63.73.13.19
facebookUrl: https://www.facebook.com/atelierdescousettes
contactFormUrl: https://tally.so/r/wvGxVA
authorName: Isabelle Bultez
authorJobTitle: Couturière diplômée CAP
address: |-
  118 lieu dit En Rivals
  81.110 VERDALLE
streetAddress: 118 lieu dit En Rivals
addressLocality: Verdalle
postalCode: '81110'
addressRegion: Tarn
defaultCtaLabel: Demande d'information
