siteName: L'Atelier des Cousettes
email: info@couture-tarn.fr
phones:
  - 06.95.78.36.34
  - 05.63.73.13.19
facebookUrl: https://www.facebook.com/atelierdescousettes
googleBusinessUrl: https://www.google.com/maps/place/L'Atelier+des+Cousettes/@43.5208069,2.1482666,17z/data=!3m1!4b1!4m6!3m5!1s0x12ae1544ec51a2a5:0x759d51dff807c372!8m2!3d43.5208069!4d2.1482666!16s%2Fg%2F11t9mjs9ht
contactFormUrl: https://tally.so/r/wvGxVA
authorName: Isabelle Bultez
authorJobTitle: Couturière diplômée CAP
address: |-
  118 lieu dit En Rivals
  81.110 VERDALLE
streetAddress: 118 lieu dit En Rivals
addressLocality: Verdalle
postalCode: '81110'
addressRegion: Tarn
defaultCtaLabel: Demande d'information
